---
title: "Restrictions"
author: "Maria Migrova"
date: "12/5/2021"
output: html_document
---

```{r}
library(tidyr)
library(dplyr)

```

```{r}
stringency.df <- read.csv("covid-stringency-index.csv",fileEncoding = "UTF-8-BOM")
masks.df <- read.csv("face-covering-policies-covid.csv",fileEncoding = "UTF-8-BOM")
stayhome.df <- read.csv("stay-at-home-covid.csv",fileEncoding ="UTF-8-BOM")
cases.df <- read.csv("owid-covid-data.csv",fileEncoding = "UTF-8-BOM")

```

```{r}
stringency1.df <- stringency.df %>%
  rename(Country = Entity , ISO = Code, Date = Day)

stringency1.df$Date <- as.Date(stringency1.df$Date, format = "%d/%m/%Y")


stringency_final.df <- stringency1.df[stringency1.df$Date > "2020-12-31" & stringency1.df$Date < "2021-11-24",]
stringency_final.df


```

```{r}
cases1.df <- cases.df %>%
  select(location,iso_code, date,total_cases,new_cases)%>%
  rename(Country = location, ISO = iso_code)
cases1.df
```


```{r}
masks1.df <- masks.df %>%
  rename(Country = Entity, ISO = Code, Date = Day)


masks1.df$Date <- as.Date(masks1.df$Date, format = "%d/%m/%Y")


masks_final.df <- masks1.df[masks1.df$Date > "2020-12-31" & masks1.df$Date < "2021-11-24",]
masks_final.df
masks_final.df

```

```{r}
stayhome1.df <- stayhome.df %>%
  rename(Country = Entity, ISO = Code, Date = Day)

stayhome1.df$Date <- as.Date(stayhome1.df$Date, format = "%d/%m/%Y")


stayhome_final.df <- stayhome1.df[stayhome1.df$Date > "2020-12-31" & stayhome1.df$Date < "2021-11-24",]
stayhome_final.df

```

```{r}
string_masks.df <- full_join(stringency_final.df,masks_final.df, by= c("ISO","Date"))

```

```{r}
string_masks.df

```

```{r}
restrictions.df <- full_join(string_masks.df, stayhome_final.df, by = c("ISO","Date"))

```

```{r}
restrictions.df <- restrictions.df %>%
  select(ISO, Country.x,Date, stringency_index, facial_coverings, stay_home_requirements)%>%
  rename(Country = Country.x)
restrictions.df

```
```{r}
restrictions_final.df <- restrictions.df %>%
  group_by(Country)%>%
  summarise(MaxStringencyIndex = max(stringency_index),
            MeanStringencyIndex = mean(stringency_index),
            MaxFacialCoverings = max(facial_coverings),
            MeanFacialCoverings = mean(facial_coverings),
            MaxStayHome = max(stay_home_requirements),
            MeanStayHome = mean(stay_home_requirements))
restrictions_final.df
```
```{r}
ISO <- restrictions.df %>%
  select(ISO, Country)%>%
  distinct(ISO,Country)

ISO

```
```{r}
restrictions_final1.df <- right_join(ISO,restrictions_final.df, by= c("Country"))
restrictions_final1.df <- restrictions_final1.df %>%
  rename(isocode = ISO, country = Country)
restrictions_final1.df <- restrictions_final1.df[-c(186:205),]
```

```{r}

restrictions_final1.df
```

```{r}
write.csv(restrictions_final1.df, "restrictions.csv")

```