---
title: "DB project"
author: "Maria Migrova"
date: "12/4/2021"
output: html_document
---


```{r}
#libraries
library(stringr)
library(tidyr)
library(dplyr)
library(rpart)
library(randomForest)
library(openair)
library(lubridate)
library(party)
library(ggplot2)
```

```{r}
#Reading data
testing.df <- read.csv("SLOVAKIA TESTING.csv",fileEncoding = "UTF-8-BOM")
testing.df

```

```{r}
#Separating columns
testing1.df <- testing.df %>%
  separate(X.Date...Region...District...District_code...Gender...AgeGroup...PCR_Pos...PCR_Neg...PCR_Total.,sep=";",c("Date","Region","District","DistrictCode","Gender","AgeGroup","PCRPos","PCRNeg","PCRTotal"))
```

```{r}
#Creating age categories
testing1.df[testing1.df == "\"00\""] <- 1
testing1.df[testing1.df == "\"01-04\""] <- 1
testing1.df[testing1.df == "\"05-09\""] <- 1
testing1.df[testing1.df == "\"10-14\""] <- 1
testing1.df[testing1.df == "\"15-19\""] <- 1
testing1.df[testing1.df == "\"20-24\""] <- 2
testing1.df[testing1.df == "\"25-34\""] <- 2
testing1.df[testing1.df == "\"35-44\""] <- 3
testing1.df[testing1.df == "\"45-54\""] <- 3
testing1.df[testing1.df == "\"55-64\""] <- 4
testing1.df[testing1.df == "\"65_v\""] <- 4
testing1.df[testing1.df == "\"neznáme\""] <- 4
testing1.df[testing1.df == "\"999\""] <- 4
```

```{r}
#Creating categories where Pos is bigger or smaller than Neg
testing2.df <- testing1.df %>%
  mutate(Status = case_when(
    PCRPos > PCRNeg ~ "1",
    PCRPos < PCRNeg ~ "2"
  ))
testing2.df
```
```{r}

#Removing NA values
testing2.df$Status[is.na(testing2.df$Status)] <-0
testing2.df <- subset(testing2.df,Gender != "NA")

testing2.df


```

```{r}
testing2.df
```



```{r}
#CHanging data types
testing2.df$Date <- as.Date(testing2.df$Date)
testing2.df$AgeGroup <- as.numeric(testing2.df$AgeGroup)
testing2.df$PCRPos <- as.numeric(testing2.df$PCRPos)
testing2.df$PCRNeg <- as.numeric(testing2.df$PCRNeg)
testing2.df$PCRTotal <- as.numeric(testing2.df$PCRTotal)
testing2.df$Status <- as.numeric(testing2.df$Status)
testing2.df$Gender <- as.factor(testing2.df$Gender)
testing2.df$Status <- as.factor(testing2.df$Status)

```

```{r}
testing2.df
class(testing2.df)

```

```{r}
#Picking data from till
testing_final1.df <- testing2.df[testing2.df$Date > "2021-01-01" & testing2.df$Date < "2021-12-01",]
testing_final1.df
```
```{r}
write.csv(testing_final1.df,"SlovakiaTesting2021.csv")

```

```{r}
#Creating Random Forest Model
model1 <- ctree(Status ~ Gender + AgeGroup, data=testing_final1.df)
plot(model1)
#Saving the plot
jpeg('plot1.jpg',width=1000)
```
